config/routes.rb
Rails.application.routes.draw do
  get 'every_camp/index'
  get 'areas/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'admin_camps', to: 'camps#admin_index'

  resources :users, only: %i[new index create show edit update destroy] do
    resources :every_camp, only: %i[index] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :items, only: %i[index new create destroy]
  resources :user_items, only: %i[index create destroy]
  resources :search_user_items, only: %i[index]
  resources :makers, only: %i[index new create update destroy]
  resources :camps, only: %i[index new create show edit update destroy] do
    resources :camp_items, only: %i[index new create show destroy]
    get 'search_items', to: 'camp_items#search_items'
    get 'my_items', to: 'camp_items#my_items'
    post 'add_my_items', to: 'camp_items#add_my_items'
    resources :areas, only: %i[index create destroy]
  end
  resources :password_resets, only: %i[new create edit update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def top
    @camps = Camp.includes(:area,
                            user: { avatar_attachment: :blob }).with_attached_images.order('created_at DESC').page(params[:page]).per(10).without_count
    @like = Like.new
    @items = Item.joins(:user_items).group(:id).order('count(user_id) desc').includes([:maker]).with_attached_small_image.page(params[:page]).per(10)
  end

  def terms; end

  def privacy_policy; end
end

app/views/static_pages/_camp_list.html.erb
    <% @camps.each do |camp| %>
      <div class="col-lg-6 col-sm-12 card-group mt-3">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="container">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(camp.user), style: "display: inline-block;" %>
                  <span class="ml-2"><%= camp.user.name%></span>
                  <span class="text-white-50"><%= "・#{camp.camped_on}"%></span>
                </div>
              </div>
            </div>
          </div>
          <%= link_to camp_path(camp.id), style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="container">
              <div class="row">
                <!-- 画像1枚のとき-->
                <% if camp.images.count == 1 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <%= image_tag(camp.images[0].variant(gravity: :center, resize: "300x300^", crop:"400x290+0+0"),class: "d-block mx-auto rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_0")%>
                    <div class="none" style="display: none;">
                      <%= image_tag(camp.images[0], class: "d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_0")%>
                    </div>
                  </div>
                <% end %>

                <!-- 画像2枚のとき-->
                <% if camp.images.count == 2 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <div class='col-6'>
                          <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <%end%>

                <!-- 画像3枚のとき-->
                <% if camp.images.count >= 3 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <% if i == 0 %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                          </div>
                        <% else %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <%= image_tag(camp.images[i+1].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img mt-2", id: "camp_id_#{camp.id}_image_id_#{i+1}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                              <%= image_tag(camp.images[i+1], class: "image d-block mx-auto rounded",id: "modal_camp_id_#{camp.id}_image_id_#{i+1}")%>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          <% end %>
          <div class="card-body">
            <% if camp.area.present? %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i>
                <%= camp.area.name %>
              </p>
            <% else %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
            <% end%>
            <h2 class="card-title text-bold"><%= camp.title %></h2>
            <p class="card-text"><%= camp.note %></p>
          </div>
          <%end%>
        </div>
      </div>
    <% end %>

app/views/static_pages/_item_list.html.erb
<% if @items.present? %>
<div class="container container-m mt-3">
  <div class="row">
      <% @items.each do |item| %>
        <div class="col-lg-3 col-sm-4 card-group">
          <div class="card justify-content-around bg-dark border border-secondary mb-3">
            <% if item.small_image.present? %>
              <%= image_tag(item.small_image, style: "width: 128px;height: 128px;", class: "card-img-top mx-auto d-block") %>
            <% end %>
            <div class="card-body">
              <p class="card-title"><%= "#{product_name(item.name)[0..20]}..." %></p>
              <p class="card-text text-white-50"><%= translate_maker_name(item.maker.name) if item.maker.present? %></p>
              <% if item.product_url.present? %>
                <%= link_to item.product_url, class: 'text-white-50', data: { confirm: '楽天で商品情報を確認しますか？' }, target: :_blank, rel: "noopener noreferrer" do %>
                  <i class="fas fa-external-link-alt fa-fw text-white-50"></i>商品HPをみる
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
<% end %>

app/views/static_pages/_not_login_camp_list.html.erb
    <% @camps.each do |camp| %>
      <div class="col-lg-6 col-sm-12 card-group mt-3">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="container">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              login_path(email: 'guest_user@example.com', password: 'password'), method: :post, data: { confirm: 'ゲストユーザーでログインしますか？' }, style: "display: inline-block;" %>
                  <span class="ml-2"><%= camp.user.name%></span>
                  <span class="text-white-50"><%= "・#{camp.camped_on}"%></span>
                </div>
              </div>
            </div>
          </div>
          <%= link_to login_path(email: 'guest_user@example.com', password: 'password'), method: :post, data: { confirm: 'ゲストユーザーでログインしますか？' }, style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="container">
              <div class="row">
                <!-- 画像1枚のとき-->
                <% if camp.images.count == 1 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <%= image_tag(camp.images[0].variant(gravity: :center, resize: "300x300^", crop:"400x290+0+0"),class: "d-block mx-auto rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_0")%>
                    <div class="none" style="display: none;">
                      <%= image_tag(camp.images[0], class: "d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_0")%>
                    </div>
                  </div>
                <% end %>

                <!-- 画像2枚のとき-->
                <% if camp.images.count == 2 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <div class='col-6'>
                          <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <%end%>

                <!-- 画像3枚のとき-->
                <% if camp.images.count >= 3 %>
                  <div class="align-items-center col-lg-12 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <% if i == 0 %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                          </div>
                        <% else %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <%= image_tag(camp.images[i+1].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img mt-2", id: "camp_id_#{camp.id}_image_id_#{i+1}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                              <%= image_tag(camp.images[i+1], class: "image d-block mx-auto rounded",id: "modal_camp_id_#{camp.id}_image_id_#{i+1}")%>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          <% end %>
          <div class="card-body">
            <% if camp.area.present? %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i>
                <%= camp.area.name %>
              </p>
            <% else %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
            <% end%>
            <h2 class="card-title text-bold"><%= camp.title %></h2>
            <p class="card-text"><%= camp.note %></p>
          </div>
          <%end%>
        </div>
      </div>
    <% end %>

app/views/static_pages/privacy_policy.html.erb
<% set_meta_tags title: 'プライバシーポリシー' %>
<div class="container pt-3">
<h3>プライバシーポリシー</h3>
<p>本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

<h5 class="mt-4">第1条（個人情報）</h5>
<p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>

<h5 class="mt-4">第2条（個人情報を利用する目的）</h5>
<p>本サービスが個人情報を収集・利用する目的は，以下のとおりです。</p>
<ol>
<li>本サービスサービスの提供・運営のため</li>
</ol>

<h5 class="mt-4">第3条（個人情報の第三者提供）</h5>
<ol>
<li>本サービスは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
<ol>
<li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
<li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
<li>予め次の事項を告知あるいは公表し，かつ本サービスが個人情報保護委員会に届出をしたとき
<ol>
<li>利用目的に第三者への提供を含むこと</li>
<li>第三者に提供されるデータの項目</li>
<li>第三者への提供の手段または方法</li>
<li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
<li>本人の求めを受け付ける方法</li>
</ol></li></ol></li>
<li>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
<ol>
<li>本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
<li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
<li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
</ol></li>
</ol>

<h5 class="mt-4">第4条（プライバシーポリシーの変更）</h5>
<ol>
<li>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
<li>本サービスが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
</ol>

<p class="tR pb-5">以上</p>
</div>

app/views/static_pages/terms.html.erb
<% set_meta_tags title: '利用規約' %>
<div class="container pt-3">
<h3>利用規約</h3>

<p>この利用規約（以下，「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

<h5 class="mt-4">第1条（適用 </h5>
<ol>
<li>本規約は，ユーザーと本サービスとの間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
</ol>

<h5 class="mt-4">第2条（利用登録）</h5>
<ol>
<li>本サービスにおいては，登録希望者が本規約に同意の上，本サービスの定める方法によって利用登録を申請し，本サービスがこの承認を登録希望者に通知することによって，利用登録が完了するものとします。</li>
</ol>

<h5 class="mt-4">第3条（ユーザーIDおよびパスワードの管理）</h5>
<ol>
<li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
<li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。本サービスは，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
<li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，本サービスに故意又は重大な過失がある場合を除き，本サービスは一切の責任を負わないものとします。</li>
</ol>

<h5 class="mt-4">第4条（禁止事項）</h5>
<p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
<ol>
<li>法令または公序良俗に違反する行為</li>
<li>本サービス，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
<li>本サービスのサービスの運営を妨害するおそれのある行為</li>
<li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
<li>不正アクセスをし，またはこれを試みる行為</li>
<li>他のユーザーに成りすます行為</li>
<li>本サービス，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
<li>以下の表現を含み，または含むと本サービスが判断する内容を本サービス上に投稿し，または送信する行為
<ol>
<li>過度に暴力的な表現</li>
<li>露骨な性的表現</li>
<li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
<li>その他反社会的な内容を含み他人に不快感を与える表現</li>
</ol></li>
<li>以下を目的とし，または目的とすると本サービスが判断する行為
<ol>
<li>営業，宣伝，広告，勧誘，その他営利を目的とする行為（本サービスの認めたものを除きます。）</li>
<li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
<li>本サービス，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
</ol></li>
</ol>

<h5 class="mt-4">第5条（本サービスの提供の停止等）</h5>
<ol>
<li>本サービスは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
<ol>
<li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
<li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
<li>コンピュータまたは通信回線等が事故により停止した場合</li>
<li>その他，本サービスが本サービスの提供が困難と判断した場合</li>
</ol></li>
<li>本サービスは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
</ol>

<h5 class="mt-4">第6条（著作権）</h5>
<ol>
<li>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。</li>
<li>ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，本サービスは，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</li>
<li>前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて本サービスまたは本サービスにその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</li>
</ol>

<h5 class="mt-4">第7条（利用制限および登録抹消）</h5>
<ol>
<li>本サービスは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
<ol>
<li>本規約のいずれかの条項に違反した場合</li>
<li>本サービスからの連絡に対し，一定期間返答がない場合</li>
<li>本サービスについて，最終の利用から一定期間利用がない場合</li>
<li>その他，本サービスが本サービスの利用を適当でないと判断した場合</li>
</ol></li>
<li>前項各号のいずれかに該当した場合，ユーザーは，当然に本サービスに対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
<li>本サービスは，本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
</ol>

<h5 class="mt-4">第8条（退会）</h5>
<p>ユーザーは，本サービスの定める退会手続により，本サービスから退会できるものとします。</p>

<h5 class="mt-4">第9条（サービス内容の変更等）</h5>
<p>本サービスは，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

<h5 class="mt-4">第10条（利用規約の変更）</h5>
<p>本サービスは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>

<h5 class="mt-4">第11条（個人情報の取扱い）</h5>
<p>本サービスは，本サービスの利用によって取得する個人情報については，本サービス「プライバシーポリシー」に従い適切に取り扱うものとします。</p>

<h5 class="mt-4">第12条（通知または連絡）</h5>
<p>ユーザーと本サービスとの間の通知または連絡は，本サービスの定める方法によって行うものとします。本サービスは,ユーザーから,本サービスが別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>

<h5 class="mt-4">第13条（権利義務の譲渡の禁止）</h5>
<p class="pb-5">ユーザーは，本サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
</div>

app/views/static_pages/top.html.erb
<% set_meta_tags title: 'Top' %>
  <div id="headerwrap">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 text-center">
          <br/>
          <br/>
          <h2>あの日の、あの火を。<br/>
					- さあ、TAKiBee -</h2>
          <br/>
          <br/>
          <% if logged_in? %>
            <div class='text-center'>
              <%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'ログアウトしますか？' } %>
            </div>
            <br>
          <% else %>
            <div class='text-center'>
              <%= link_to '新規登録', new_user_path, class: 'btn btn-outline-warning' %>
            </div>
            <br>
            <div class='text-center'>
              <%= link_to 'ログイン', login_path, class: 'btn btn-outline-warning' %>
            </div>
            <br>
            <div class='text-center'>
              <%= link_to 'ゲストユーザーでログイン', login_path(email: 'guest_user@example.com', password: 'password'), method: :post, class: 'btn btn-outline-warning' %>
            </div>
          <% end %>
        </div>
        <!-- /col-lg-6 -->
        <div class="col-lg-6 text-center">
          <%= image_tag 'camping.png', class: 'img-responsive', style: 'height:auto; width:100%;'%>
        </div>
        <!-- /col-lg-6 -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /headerwrap -->

  <div class="container">
    <div class="row mt centered">
      <div class="col-lg-6 col-lg-offset-3">
        <h2>キャンプの記録を<br/>TAKiBeeで残そう。</h2><br>
        <h3>たき火、ごはん、キャンプギア、<br/>あなたのキャンプを記録できます。</h3>
      </div>
    </div>
    <!-- /row -->
    <br/>
    <br/>


    <div class="row mt centered">
      <div class="col-lg-4 text-center">
        <%= image_tag 'item-1.png',style: 'width:180px;'%>
        <h4>1 - アイテムの登録</h4>
        <p>キャンプギアを検索して、登録できます。<br/>自分のキャンプギアを整理しよう。</p>
      </div>
      <!--/col-lg-4 -->

      <div class="col-lg-4 text-center">
        <%= image_tag 'item-2.png',style: 'width:180px;'%>
        <h4>2 - キャンプの記録</h4>
        <p>キャンプの写真や場所、持って行った<br/>キャンプギアを記録しよう。</p>

      </div>
      <!--/col-lg-4 -->

      <div class="col-lg-4 text-center">
        <%= image_tag 'item-3.png',style: 'width:180px;'%>
        <h4>3 - 投稿のシェア</h4>
        <p>記録したキャンプ・アイテムを投稿しよう。<br/>みんなのキャンプを覗いてみよう。</p>

      </div>
      <!--/col-lg-4 -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
  <br/>
  <br/>

  <div class="container">
    <% if logged_in? %>
      <div class='text-center'>
        <%= link_to "http://twitter.com/share?url=https://www.takibee.net/&text=TAKiBEEでキャンプの記録を残そう！/&hashtags=TAKiBEE", title: 'Twitter', target: '_blank' do %>
          <i class="fab fa-twitter btn btn-info"></i>
        <% end %>
      <% else %>
        <div class='text-center'>
          <%= link_to '新規登録', new_user_path, class: 'btn btn-outline-warning' %>
        </div>
        <br>
        <div class='text-center'>
          <%= link_to 'ログイン', login_path, class: 'btn btn-outline-warning' %>
        </div>
        <br>
        <div class='text-center'>
          <%= link_to 'ゲストユーザーでログイン', login_path(email: 'guest_user@example.com', password: 'password'), method: :post, class: 'btn btn-outline-warning' %>
        </div>
        <br>
        <div class='text-center'>
          <%= link_to "http://twitter.com/share?url=https://www.takibee.net/&text=TAKiBEEでキャンプの記録を残そう！/&hashtags=TAKiBEE", title: 'Twitter', target: '_blank' do %>
            <i class="fab fa-twitter btn btn-info"></i>
          <% end %>
        <% end %>
      </div>
  </div>

  <div class="row mt centered mt-5">
    <div class="col-12 text-center">
        <h4>ー 最新の投稿 ー</h4>
    </div>
    <% if current_user.present? %>
      <%= render "camp_list" %>
    <% else %>
      <%= render "not_login_camp_list"%>
    <% end %>
  </div>
  <div class="row mt centered mt-5">
    <div class="col-12 text-center">
        <h4>ー 人気アイテム ー</h4>
    </div>
    <%= render "item_list" %>
    <%= render partial: 'every_camp/modal' %>
  </div>

  <%= render "/shared/footer" %>