config/routes.rb
Rails.application.routes.draw do
  get 'every_camp/index'
  get 'areas/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'admin_camps', to: 'camps#admin_index'

  resources :users, only: %i[new index create show edit update destroy] do
    resources :every_camp, only: %i[index] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :items, only: %i[index new create destroy]
  resources :user_items, only: %i[index create destroy]
  resources :search_user_items, only: %i[index]
  resources :makers, only: %i[index new create update destroy]
  resources :camps, only: %i[index new create show edit update destroy] do
    resources :camp_items, only: %i[index new create show destroy]
    get 'search_items', to: 'camp_items#search_items'
    get 'my_items', to: 'camp_items#my_items'
    post 'add_my_items', to: 'camp_items#add_my_items'
    resources :areas, only: %i[index create destroy]
  end
  resources :password_resets, only: %i[new create edit update]
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :items
  belongs_to :user
  has_many :camp_items, dependent: :destroy
  has_many :items, class_name: 'Item', foreign_key: 'item_id', through: :camp_items, source: 'item'
  has_many_attached :images
  has_one :area
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true
  validate :images_size

  def images_size
    images.each do |image|
      if image.blob.byte_size > 5.megabytes
        errors.add(:avatars, 'は1つのファイル5MB以内にしてください')
      end
    end
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  include UsersHelper
  before_action :require_signup, only: %i[new]

  def admin_index
    if current_user.is_admin_user?
      @camps = Camp.includes(:area,
                             user: { avatar_attachment: :blob }).with_attached_images.order('created_at DESC')
    else
      redirect_to user_every_camp_index_path(current_user)
    end
  end

  def index
    @camps = current_user.camps.includes(:area).with_attached_images.order('camped_on DESC')
  end

  def new
    @camp = Camp.new
  end

  def show
    @camp = Camp.with_attached_images.find(params[:id])
    @items = @camp.items.includes(:maker).with_attached_small_image
  end

  def edit
    @camp = Camp.with_attached_images.find(params[:id])
    redirect_to camps_path unless current_user == @camp.user
  end

  def create
    @camp = current_user.camps.new(camp_params)
    if @camp.save
      redirect_to camps_path
    else
      render 'new'
    end
  end

  def update
    @camp = Camp.find(params[:id])
    if params[:image_id].present?
      image = @camp.images&.find(params[:image_id])
      image.purge
      @items = @camp.items
      redirect_to edit_camp_path(@camp)
    else
      if @camp.update(camp_params)
        redirect_to camp_path(@camp)
      else
        render 'edit'
      end
    end
  end

  def destroy
    @camp = Camp.find(params[:id])
    @camp.destroy!
    redirect_to camps_path
  end

  private

    def camp_params
      params.require(:camp).permit(:title, :camped_on, :number_of_people, :note, images: [])
    end
end

app/helpers/camp_helper.rb
module CampHelper
  def split_lat(string)
    string[1..-1].chop.split(',')[0]
  end

  def split_lng(string)
    string[1..-1].chop.split(',')[1]
  end
end

app/views/camps/_admin_camp_list.html.erb
<% if @camps.present? %>
<p class='pt-3 text-warning'><%= "投稿数：#{@camps.count}" %></p>
<table class="table table-hover">
    <thead>
        <tr>
          <th>Camp_id</th>
          <th>User</th>
          <th>Img</th>
          <th>Title</th>
          <th>Area</th>
          <th>Date</th>
          <th>Comment</th>
          <th>Items</th>
          <th>Btn</th>
        </tr>
    </thead>
    <tbody>
      <% @camps.each do |camp| %>
        <tr class="clickable-row", data-link="<%= camp_path(camp) %>">
          <td><%= camp.id %></td>
          <% if camp.user.avatar.present? %>
          <td>
          <%= link_to image_tag(camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(camp.user), style: "display: inline-block;" %>
          <br>
              <%= camp.user.name %>
          </td>
          <% else %>
          <td></td>
          <% end %>
          <% if camp.images.present? %>
          <td><%= image_tag(camp.images[0].variant(gravity: :center, resize: "100x100^", crop:"100x100+0+0")) %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.title %></td>
          <% if camp.area.present? %>
          <td><%= camp.area.name %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.camped_on %></td>
          <td><%= camp.note %></td>
          <td><%= camp.items.count%></td>
          <td>
            <%= link_to '削除', camp_path(camp.id), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除しますか？' }%>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
<% end %>

app/views/camps/_camp_cards_list.html.erb
  <div class='row'>
    <% @camps.each do |camp|%>
      <div class="col-lg-3 col-md-4 col-sm-4 card-group shadow-sm mt-3">
        <div class="card bg-dark border border-secondary ">
          <%= link_to camp_path(camp.id), style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="align-items-center">
              <%= image_tag(camp.images[0].variant(gravity: :center, resize: "300x300^", crop:"300x300+0+0"),class: "d-block mx-auto rounded img-fluid")%>
            </div>
          <% end %>
          <div class="card-body">
            <h2 class="card-title"><%= camp.title %></h2><br>
            <p class="text-white-50">
              <i class="fas fa-calendar-alt"></i>
              <%= camp.camped_on %>
            </p>
            <% if camp.area.present? %>
              <p class="text-white-50">
                <i class="fas fa-map-marker-alt"></i>
                <%= camp.area.name %>
              </p>
              <% else %>
                <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
            <% end %>

            <p class="card-text"><%= camp.note %></p>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/camps/_camp_image_list.erb
<% if @camp.images.present? %>
  <div class="row">
    <% @camp.images.each do |image| %>
      <div class="col-md-3">
        <div class="image-box">
            <%= link_to camp_path(camp_id: @camp.id, image_id: image.id),
                        method: :patch, class: 'picture_delete_button', style: "display: none;" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-x-square" viewBox="0 0 16 16" >
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
</svg>
            <%end%>
          <%= image_tag image.variant(combine_options:{gravity: :center, resize: "200x200^", crop:"200x200+0+0"}), class: "img-thumbnail mb-3" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/camps/_camp_image_list.html.erb
<% if @camp.images.present? %>
  <div class="row">
    <% @camp.images.each do |image| %>
      <div class="col-md-3 col-sm-6">
        <div class="image-box">
            <%= link_to camp_path(camp_id: @camp.id, image_id: image.id),
                        method: :patch, class: 'picture_delete_button', style: "display: none;" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-x-square" viewBox="0 0 16 16" >
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
</svg>
            <%end%>
          <%= image_tag image.variant(gravity: :center, resize: "200x200^", crop:"200x200+0+0"), class: "img-thumbnail mb-3" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/camps/_camp_list.erb
<% if @camps.present? %>
<table class="table table-hover">
    <thead>
        <tr>
          <th>Img</th>
          <th>Title</th>
          <th>Area</th>
          <th>Date</th>
          <th>Comment</th>
        </tr>
    </thead>
    <tbody>
      <% @camps.each do |camp| %>
        <tr class="clickable-row", data-link="<%= camp_path(camp) %>">
          <% if camp.images.present? %>
          <td><%= image_tag(camp.images[0].variant(combine_options:{gravity: :center, resize: "100x100^", crop:"100x100+0+0"})) %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.title %></td>
          <% if camp.area.present? %>
          <td><%= camp.area.name %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.camped_on %></td>
          <td><%= camp.note %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<% end %>

app/views/camps/_camp_list.html.erb
<% if @camps.present? %>
<table class="table table-hover">
    <thead>
        <tr>
          <th>Img</th>
          <th>Title</th>
          <th>Area</th>
          <th>Date</th>
          <th>Comment</th>
        </tr>
    </thead>
    <tbody>
      <% @camps.each do |camp| %>
        <tr class="clickable-row", data-link="<%= camp_path(camp) %>">
          <% if camp.images.present? %>
          <td><%= image_tag(camp.images[0].variant(gravity: :center, resize: "100x100^", crop:"100x100+0+0")) %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.title %></td>
          <% if camp.area.present? %>
          <td><%= camp.area.name %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= camp.camped_on %></td>
          <td><%= camp.note %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<% end %>

app/views/camps/_item_list.erb
<% if @items.present? %>
<div class="container container-m">
  <div class="row">
      <% @items.each do |item| %>
        <div class="col-md-4 card-group">
          <div class="card justify-content-around bg-dark border border-secondary mb-3">
              <%= link_to camp_camp_item_path(camp_id: @camp.id, item_id: item.id), method: :delete, class: 'item_delete_button', style: "display: none;" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-x-square float-right" viewBox="0 0 16 16" >
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
              <%end%>
            <% if item.small_image.present? %>
              <%= image_tag(item.small_image, style: "width: 128px;height: 128px;", class: "card-img-top mx-auto d-block") %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= "#{item.name[0..20] ...}" %></h5>
              <p class="card-text"><%= item.maker.name if item.maker.present? %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
<% end %>

app/views/camps/_item_list.html.erb
<% if @items.present? %>
<div class="container container-m">
  <div class="row">
      <% @items.each do |item| %>
        <div class="col-lg-3 col-sm-4 card-group">
          <div class="card justify-content-around bg-dark border border-secondary mb-3">
              <%= link_to camp_camp_item_path(camp_id: @camp.id, item_id: item.id), method: :delete, class: 'item_delete_button', style: "display: none;" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-x-square float-right" viewBox="0 0 16 16" >
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
              <%end%>
            <% if item.small_image.present? %>
              <%= image_tag(item.small_image, style: "width: 128px;height: 128px;", class: "card-img-top mx-auto d-block") %>
            <% end %>
            <div class="card-body">
              <p class="card-title"><%= "#{product_name(item.name)[0..20]}..." %></p>
              <p class="card-text text-white-50"><%= translate_maker_name(item.maker.name) if item.maker.present? %></p>
              <% if item.product_url.present? %>
                <%= link_to item.product_url, class: 'text-white-50', data: { confirm: '楽天で商品情報を確認しますか？' }, target: :_blank, rel: "noopener noreferrer" do %>
                  <i class="fas fa-external-link-alt fa-fw text-white-50"></i>商品HPをみる
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
<% end %>

app/views/camps/admin_index.html.erb
<div class='container'>
    <div id='camp_list' class='pb-5'>
      <% if @camps.present? %>
        <%= render partial: 'admin_camp_list' %>
      <% else %>
        <p class='text-center text-warning pt-3'>キャンプのキロクはまだありません</p>
      <% end %>
    </div>
  </div>

app/views/camps/edit.html.erb
<%= form_with model: @camp, local:true do |f| %>
<div class="container">
    <div class='content'>
      <div class="col-md-12 col card-group">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="contain">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(current_user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(current_user), style: "display: inline-block;" %>
                  <%= current_user.name%>
                </div>
              </div>
            </div>
          </div>

          <div class="card-body">
            <div class="form-group col-md-10 offset-md-1 col-lg-8 offset-lg-2">
              <div class="preview-box border rounded col-md-12">
                <%= f.label :image do%>
                  <i class="far fa-images fa-lg" style="display: inline-block;"></i> （合計5枚まで）
                  <%= f.file_field :images, multiple: true, id: :camp_image, onchange: "loadImage(this);", style: "display: none;" %>
                <% end %>
              </div>
              <div class="alert alert-warning mt-3" style="display:none;">！画像は合計で5枚以下にしてください！
              </div>
              <label for="camp_キャンプのタイトル" class="mt-3">追加する画像</label>
              <div class="contain border rounded col-md-12">
                <p class="btn btn-outline-light" id="preview-delete">選択をクリア</p>
                <div class="image_box row" id='image-box__container' style="min-height:200px;"></div>
              </div>
              <label for="camp_キャンプのタイトル" class="mt-3">登録中の画像</label>
              <div class="contain preview-box border rounded col-md-12">
                <div class="row">
                  <% if @camp.images.present? %>
                    <% @camp.images.each do |image|%>
                      <div class="col-md-4 text-center">
                        <%= image_tag image, style: "max-width:90%; max-height:500px;", class: "mt-3 added-image" %>
                        <%= link_to '削除', camp_path(camp_id: @camp.id, image_id: image.id), method: :patch, class: 'btn btn-danger mt-2 mb-2', style: "display:inline-block;" %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
              <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group">
              <%= f.label 'キャンプのタイトル' %>
              <%= f.text_field :title, class: 'form-control bg-dark' %>
            </div>
            <div class="form-group">
              <%= f.label 'コメント' %>
              <%= f.text_area :note, class: 'form-control bg-dark' %>
            </div>
            <div class="form-group">
              <%= f.label '日付' %>
              <%= f.text_field :camped_on, class: 'form-control bg-dark', id: 'datepicker' %>
            </div>
            <div class="form-group">
              <%= f.label '人数' %>
              <%= f.number_field :number_of_people, min: 1, default: 1, placeholder: 1, class: 'form-control bg-dark' %>
            </div>
            <br>
            <div class='text-center'>
              <%= f.submit (t 'defaults.register'), class: 'btn btn-outline-warning m-5 submit-button' %>
              <% end %>
              <%= link_to 'マイキャンプへ戻る', camps_path, class: 'btn btn-outline-light' %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<script>
// view/camps/editで使用
$('#datepicker').datepicker({
  dateFormat: 'yy-mm-dd'
});

var image_box = $('#image-box__container');
var number_of_added_images = $('.added-image').length;
var submit_button = $('.submit-button');
var alert_message = $('.alert-warning');

function loadImage(obj){
  //画像が選択されていれば、プレビューを削除する
  var target_image = $('.each-image-preview');
      target_image.remove();
  var number_of_add_images = 0;

  //選択された画像をプレビューで表示
	for (i = 0; i < obj.files.length; i++) {
		var fileReader = new FileReader();
		fileReader.onload = (function (e) {
      var html = `<div class="col-md-4 each-image-preview">
                    <img src="${e.target.result}" style="max-width:90%; max-height:500px;">
                  </div>`;
      image_box.append(html);
		});
		fileReader.readAsDataURL(obj.files[i]);
    number_of_add_images += 1
	};
    //画像の合計枚数を確認
    console.log(number_of_add_images + number_of_added_images);
    if (number_of_add_images + number_of_added_images > 5) {
      console.log("画像は合計5枚以下としてください");
      alert_message.fadeIn(300);
      submit_button.prop("disabled", true);
    } else {
      submit_button.prop("disabled", false);
    };
};

  //削除ボタンをクリックすると発火するイベント
  $(document).on("click", '#preview-delete', function(){
  var file_field = document.querySelector('input[type=file]');
  //削除を押されたプレビュー要素を取得
  var target_image = $('.each-image-preview');
  //inputタグに入ったファイルを削除
  $('input[type=file]').val('');
  //プレビューを削除
  target_image.remove();
  //画像が5枚以下なら登録可能とする
  if ( number_of_added_images < 5) {
    submit_button.prop("disabled", false);
    alert_message.fadeOut(300);
  };
});
</script>

app/views/camps/index.html.erb
<% set_meta_tags title: "#{t '.title'}" %>
<% content_for :title do%>
<%= t '.title' %>
<% end %>
  <div class='container'>

    <div id='camp_list' class='pb-5'>
      <% if @camps.present? %>
        <a><%= link_to '＋キャンプを記録', new_camp_path, class: 'btn btn-outline-warning btn-block'%></a>
        <%= render partial: 'camp_cards_list' %>
      <% else %>
        <p class='text-center text-warning pt-3'>キャンプのキロクはまだありません</p>
        <a><%= link_to '＋キャンプを記録', new_camp_path, class: 'btn btn-outline-warning btn-block'%></a>
      <% end %>
    </div>
  </div>

app/views/camps/show.html.erb
<% set_meta_tags title: @camp.title %>
<div class='container'>
  <%= link_to 'javascript:history.back()' do %>
  <i class="fas fa-angle-left fa-2x"></i>
  <%end%>

      <!--ドロップダウンリスト開始-->
  <% if current_user == @camp.user %>
    <div class="float-right mx-auto">
      <div class="dropleft">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="far fa-trash-alt fa-lg text-right"></i>
        </button>
      <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton">
        <%= link_to camp_path, method: :delete, data: { confirm: 'このキャンプを削除しますか？' }, class: 'dropdown-item text-danger doropdown-list-delete' do %>
          <span><i class="far fa-trash-alt"></i></span>  キャンプを削除
        <% end %>
          <a class='dropdown-item text-danger doropdown-list-delete' id="item_edit_button">
            <i class="far fa-trash-alt"></i>  アイテムを削除
          </a>
          <% if @camp.area.present? %>
            <%= link_to camp_area_path(@camp), method: :delete, data: { confirm: 'キャンプ地を削除しますか？' }, class: 'dropdown-item text-danger doropdown-list-delete' do %>
              <span><i class="fas fa-trash-alt"></i></span>  キャンプ地を削除
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
  <!--ドロップダウンリスト終わり-->
  <!--ドロップダウンリスト開始-->
  <div class="float-right mx-auto">
    <div class="dropleft">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="far fa-plus-square fa-lg text-light"></i>
              </button>
              <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton">
                <%= link_to edit_camp_path(@camp), class: 'dropdown-item text-success doropdown-list-delete' do%>
                    <i class="fas fa-plus"></i>  写真を追加・編集
                <% end %>
                <%= link_to camp_my_items_path(@camp), class: 'dropdown-item text-success doropdown-list-delete' do%>
                  <i class="fas fa-plus"></i>  アイテムを追加
                <% end %>
                <% if @camp.area.blank? %>
                  <%= link_to camp_areas_path(@camp), class: 'dropdown-item text-success doropdown-list-delete' do%>
                    <i class="fas fa-plus"></i>  キャンプ地を登録
                  <% end %>
                <% end%>
              </div>
            </div>
          </div>
        <!--ドロップダウンリスト終わり-->
      <%end%>


      <!--card形式へ変更-->
      <div class="col col card-group">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="contain">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(@camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(@camp.user), style: "display: inline-block;" %>
                  <%= @camp.user.name%><span class="text-white-50"><%= "・#{@camp.camped_on}"%></span>
                  <% if current_user.already_liked?(@camp) %>
                    <%= render partial: 'every_camp/unlike', locals: {camp: @camp} %>
                  <% else %>
                    <%= render partial: 'every_camp/like', locals: {camp: @camp} %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
                <!-- Slider main container -->
                  <div class="swiper-container">
                    <!-- Additional required wrapper -->
                    <div class="swiper-wrapper">
                      <!-- Slides -->
                      <% if @camp.images.present? %>
                        <% @camp.images.each do |image| %>
                          <div class="align-items-center js-modal-img swiper-slide">
                            <%= image_tag(image.variant(gravity: :center, resize: "300x300^", crop:"400x280+0+0"),class: "d-block mx-auto rounded img-fluid")%>
                          </div>
                        <% end %>
                      <% end %>
                    </div>

                    <!-- If we need pagination -->
                    <div class="swiper-pagination swiper-pagination-white"></div>

                    <!-- If we need navigation buttons -->
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                  </div>

          <div class="card-body">
            <% if @camp.area.present? %>
                <%= link_to "https://www.google.com/maps/search/?api=1&query=#{@camp.area.name}", data: { confirm: 'Google Mapで確認しますか？' }, target: :_blank, rel: "noopener noreferrer", class: "text-white-50" do %>
                <p class="text-white-50">
                  <i class="fas fa-map-marker-alt"></i>
                  <%= @camp.area.name %>
                <% end %>
              </p>
            <% else %>
              <% if @camp.user == current_user %>
                <%= link_to camp_areas_path(@camp), data: { confirm: 'キャンプ地を登録しますか？' } do%>
                  <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
                <% end %>
              <% else %>
                <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
              <% end %>
            <% end%>
            <h2 class="card-title text-bold"><%= @camp.title %></h2><br>
            <p class="card-text"><%= @camp.note %></p>
            <div class="row">
              <%= render partial: 'item_list', locals: {camp: @camp} %>
              <% if @camp.user == current_user && @camp.items[0].nil? %>
                <a><%= link_to '＋アイテムを追加', camp_my_items_path(@camp), class: 'btn btn-outline-warning btn-block col-md-12 mt-5'%></a>
              <% end %>
            </div>
          </div>
        </div>
      </div>


<%= javascript_pack_tag 'camp/button_display' %>

<script>
    let mySwiper = new Swiper ('.swiper-container', {
  // 以下にオプションを設定
  loop: false, //最後に達したら先頭に戻る

  //ページネーション表示の設定
  pagination: {
    el: '.swiper-pagination', //ページネーションの要素
    type: 'bullets', //ページネーションの種類
    clickable: true, //クリックに反応させる
  },

  //ナビゲーションボタン（矢印）表示の設定
  navigation: {
    nextEl: '.swiper-button-next', //「次へボタン」要素の指定
    prevEl: '.swiper-button-prev', //「前へボタン」要素の指定
  },

  //スクロールバー表示の設定
  scrollbar: {
    el: '.swiper-scrollbar', //要素の指定
  },
})
</script>