config/routes.rb
Rails.application.routes.draw do
  get 'every_camp/index'
  get 'areas/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'admin_camps', to: 'camps#admin_index'

  resources :users, only: %i[new index create show edit update destroy] do
    resources :every_camp, only: %i[index] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :items, only: %i[index new create destroy]
  resources :user_items, only: %i[index create destroy]
  resources :search_user_items, only: %i[index]
  resources :makers, only: %i[index new create update destroy]
  resources :camps, only: %i[index new create show edit update destroy] do
    resources :camp_items, only: %i[index new create show destroy]
    get 'search_items', to: 'camp_items#search_items'
    get 'my_items', to: 'camp_items#my_items'
    post 'add_my_items', to: 'camp_items#add_my_items'
    resources :areas, only: %i[index create destroy]
  end
  resources :password_resets, only: %i[new create edit update]
end

app/views/shared/_before_login_header.html.erb
<header>
<!-- Navbar -->
  <nav class='main-header navbar navbar-expand navbar-dark navbar-light fixed-top'>
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" data-turbolinks="false" ><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <a class='text-light'>
      <%= yield(:title) %>
    </a>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    </div>
  </nav>
</header>

app/views/shared/_before_login_sidebar_lte.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <%= image_tag 'takibee_icon', class: 'brand-image img-circle elevation-3' %>
    <span class="brand-text font-weight-light">TAKiBee.</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
          <%= image_tag 'sample', class: 'img-circle elevation-2' %>
      </div>
      <div class="info">
        <a class="d-block">未ログイン</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to '/', class: "nav-link #{before_login_active_if('static_pages', 'top')}" do %>
            <i class="nav-icon fas fa-fire"></i>
            <p>
              トップ
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_path, class: "nav-link #{active_if('users')}" do %>
            <i class="nav-icon fas fa-user-plus"></i>
            <p>
              新規登録
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to login_path, class: "nav-link #{before_login_active_if('user_sessions', 'new')}" do %>
            <i class="nav-icon fas fa-sign-in-alt"></i>
            <p>
              ログイン
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to terms_path, class: "nav-link #{before_login_active_if('static_pages', 'terms')}" do %>
            <i class="nav-icon fas fa-book"></i>
            <p>
              利用規約
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to privacy_policy_path, class: "nav-link #{before_login_active_if('static_pages', 'privacy_policy')}" do %>
            <i class="nav-icon fas fa-key"></i>
            <p>
              プライバシーポリシー
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer mt-5'>
  <div class='container'>
    <div class='row'>
      <div class='col-12'>
        <div class='col-md-12 text-right'>
          <%= link_to '利用規約', '/terms', class: 'text-light text-right'%>
          <%= link_to 'プライバシーポリシー', '/privacy_policy', class: 'text-light text-right'%>
          <p class='text-right'>© 2021. TAKiBee.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<!-- Navbar -->
  <nav class='main-header navbar navbar-expand navbar-dark navbar-light fixed-top'>
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" data-turbolinks="false" ><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <a class='text-light'>
      <%= yield(:title) %>
    </a>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    </div>
  </nav>
</header>

app/views/shared/_sidebar_lte.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <%= image_tag 'takibee_icon', class: 'brand-image img-circle elevation-3' %>
    <span class="brand-text font-weight-light">TAKiBee.</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
      <% if current_user.avatar.present? %>
        <%= link_to user_path(current_user) do %>
          <%= image_tag current_user.avatar.variant(gravity: :center, resize: "200x200^", crop:"200x200+0+0"), class: "rounded-circle mx-auto d-block elevation-2" %>
        <% end %>
      <% end %>
      </div>
      <div class="info">
        <a class="d-block"><%= link_to current_user.name , user_path(current_user) %></a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to user_every_camp_index_path(current_user), class: "nav-link #{active_if("every_camp")}" do %>
            <i class="nav-icon fas fa-hiking"></i>
            <p>
              みんなのキャンプ
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to camps_path, class: "nav-link #{active_if('camps')}" do %>
            <i class="nav-icon fas fa-map-signs"></i>
            <p>
              マイキャンプ
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_items_path, class: "nav-link #{active_if('user_items', 'search_user_items')}" do %>
            <i class="nav-icon fas fa-campground"></i>
            <p>
              マイアイテム
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "nav-link #{active_if('users')}" do %>
            <i class="nav-icon far fa-user"></i>
            <p>
              プロフィール
            </p>
          <% end %>
        </li>
        <% if current_user.is_guest_user? %>
          <li class="nav-item">
            <%= link_to new_user_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-user-plus"></i>
              <p>
                新規登録
              </p>
            <% end %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to logout_path, method: :delete, class: "nav-link", data: { confirm: 'ログアウトしますか？' } do %>
            <i class="nav-icon fas fa-home"></i>
            <p>
              ログアウト
            </p>
          <% end %>
        </li>

        <% if current_user.is_admin_user? %>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-user-cog"></i>
              <p>
                ユーザー一覧
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_camps_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-user-cog"></i>
              <p>
                キャンプ一覧
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-user-cog"></i>
              <p>
                アイテム一覧
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to makers_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-user-cog"></i>
              <p>
                メーカー一覧
              </p>
            <% end %>
          </li>
        <% end %>

      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>