config/routes.rb
Rails.application.routes.draw do
  get 'every_camp/index'
  get 'areas/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'admin_camps', to: 'camps#admin_index'

  resources :users, only: %i[new index create show edit update destroy] do
    resources :every_camp, only: %i[index] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :items, only: %i[index new create destroy]
  resources :user_items, only: %i[index create destroy]
  resources :search_user_items, only: %i[index]
  resources :makers, only: %i[index new create update destroy]
  resources :camps, only: %i[index new create show edit update destroy] do
    resources :camp_items, only: %i[index new create show destroy]
    get 'search_items', to: 'camp_items#search_items'
    get 'my_items', to: 'camp_items#my_items'
    post 'add_my_items', to: 'camp_items#add_my_items'
    resources :areas, only: %i[index create destroy]
  end
  resources :password_resets, only: %i[new create edit update]
end

app/controllers/every_camp_controller.rb
class EveryCampController < ApplicationController
  def index
    @camps = Camp.includes(:area,
                           user: { avatar_attachment: :blob },
                           items: { small_image_attachment: :blob }).with_attached_images.order('created_at DESC').page(params[:page]).without_count
    @like = Like.new
  end
end

app/views/every_camp/_camp_item_list.erb
<% if camp.items.present? %>
    <% camp.items.each do |item| %>
        <%= image_tag(item.small_image, style: "width: 100px;height: 100px;", class: "card-img-top mb-1 ml-1") %>
    <% end %>
<% end %>

app/views/every_camp/_camp_item_list.html.erb
<% for i in 0..11 do %>
  <% if camp.items[i].present? %>
    <%= image_tag(camp.items[i].small_image, style: "width: 100px;height: 100px;", class: "card-img-top mb-1 ml-1") %>
  <% end %>
<% end %>

app/views/every_camp/_camp_list.erb
<% if @camps.present? %>
    <% @camps.each do |camp| %>
      <div class="col-md-9 card-group">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <%= link_to image_tag(camp.user.avatar.variant(combine_options:{gravity: :center, resize: "50x50^", crop:"50x50+0+0"}), class: "rounded-circle"),
                        user_path(camp.user), style: "display: inline-block;" %>
            <%= camp.user.name%>
          </div>
          <%= link_to camp_path(camp.id), style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="align-items-center">
              <%= image_tag(camp.images[0].variant(combine_options:{gravity: :center, resize: "300x300^", crop:"400x280+0+0"}),class: "d-block mx-auto rounded img-fluid")%>
            </div>
          <% end %>
          <div class="card-body">
              <h5 class="card-title"><%= camp.title %></h5>
              <p class="card-text"><%= camp.note %></p>
            <div class="row">
              <%= render partial: 'camp_item_list', locals: {camp: camp} %>
            </div>
          </div>
          <%end%>
        </div>
      </div>
    <% end %>
<% end %>

app/views/every_camp/_camp_list.html.erb
    <% @camps.each do |camp| %>
      <div class="col-12 col card-group">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="container">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(camp.user), style: "display: inline-block;" %>
                  <span class="ml-2"><%= camp.user.name%></span>
                  <span class="text-white-50"><%= "・#{camp.camped_on}"%></span>
                  <% if current_user.already_liked?(camp) %>
                    <%= render partial: 'every_camp/unlike', locals: {camp: camp} %>
                  <% else %>
                    <%= render partial: 'every_camp/like', locals: {camp: camp} %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <%= link_to camp_path(camp.id), style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="container">
              <div class="row">
                <!-- 画像1枚のとき-->
                <% if camp.images.count == 1 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <%= image_tag(camp.images[0].variant(gravity: :center, resize: "300x300^", crop:"400x290+0+0"),class: "d-block mx-auto rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_0")%>
                    <div class="none" style="display: none;">
                      <%= image_tag(camp.images[0], class: "d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_0")%>
                    </div>
                  </div>
                <% end %>

                <!-- 画像2枚のとき-->
                <% if camp.images.count == 2 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <div class='col-6'>
                          <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <%end%>

                <!-- 画像3枚のとき-->
                <% if camp.images.count >= 3 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <% if i == 0 %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                          </div>
                        <% else %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <%= image_tag(camp.images[i+1].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img mt-2", id: "camp_id_#{camp.id}_image_id_#{i+1}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                              <%= image_tag(camp.images[i+1], class: "image d-block mx-auto rounded",id: "modal_camp_id_#{camp.id}_image_id_#{i+1}")%>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <%end%>


                <div class="col-lg-6 col-sm-12 mt-2">
                  <% if camp.items[0].present?%>
                    <%= render partial: 'every_camp/camp_item_list', locals: {camp: camp} %>
                  <% else %>
                    <div class="text-white-50 d-flex align-items-center justify-content-center" style="height:300px;">アイテムは未登録です</div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="card-body">
            <% if camp.area.present? %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i>
                <%= camp.area.name %>
              </p>
            <% else %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
            <% end%>
            <h2 class="card-title text-bold"><%= camp.title %></h2>
            <p class="card-text"><%= camp.note %></p>
          </div>
          <%end%>
        </div>
      </div>
    <% end %>

app/views/every_camp/_favorite_camp_list.html.erb
    <% @favorite_camps.each do |camp| %>
      <div class="col-12 col card-group">
        <div class="card bg-dark border border-secondary">
          <div class="card-header">
            <div class="container">
              <div class="row">
                <div class="col align-items-center">
                  <%= link_to image_tag(camp.user.avatar.variant(gravity: :center, resize: "50x50^", crop:"50x50+0+0"), class: "rounded-circle"),
                              user_path(camp.user), style: "display: inline-block;" %>
                  <span class="ml-2"><%= camp.user.name%></span>
                  <span class="text-white-50"><%= "・#{camp.camped_on}"%></span>
                  <% if current_user.already_liked?(camp) %>
                    <%= render partial: 'every_camp/unlike', locals: {camp: camp} %>
                  <% else %>
                    <%= render partial: 'every_camp/like', locals: {camp: camp} %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <%= link_to camp_path(camp.id), style:"text-decoration:none; color:black;" do %>
          <% if camp.images.present? %>
            <div class="container">
              <div class="row">
                <!-- 画像1枚のとき-->
                <% if camp.images.count == 1 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <%= image_tag(camp.images[0].variant(gravity: :center, resize: "300x300^", crop:"400x290+0+0"),class: "d-block mx-auto rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_0")%>
                    <div class="none" style="display: none;">
                      <%= image_tag(camp.images[0], class: "d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_0")%>
                    </div>
                  </div>
                <% end %>

                <!-- 画像2枚のとき-->
                <% if camp.images.count == 2 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <div class='col-6'>
                          <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <%end%>

                <!-- 画像2枚のとき-->
                <% if camp.images.count >= 3 %>
                  <div class="align-items-center col-lg-6 col-sm-12 mt-2">
                    <div class='row'>
                      <% for i in 0..1 %>
                        <% if i == 0 %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "300x300^", crop:"200x290+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                            </div>
                          </div>
                        <% else %>
                          <div class='col-6'>
                            <%= image_tag(camp.images[i].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img", id: "camp_id_#{camp.id}_image_id_#{i}")%>
                            <%= image_tag(camp.images[i+1].variant(gravity: :center, resize: "200x200^", crop:"200x140+0+0"),class: "mx-auto d-block rounded img-fluid js-modal-img mt-2", id: "camp_id_#{camp.id}_image_id_#{i+1}")%>
                            <div class="none" style="display: none;">
                              <%= image_tag(camp.images[i], class: "image d-block mx-auto rounded", id: "mx-auto d-block rounded img-fluid", id: "modal_camp_id_#{camp.id}_image_id_#{i}")%>
                              <%= image_tag(camp.images[i+1], class: "image d-block mx-auto rounded", id: "mx-auto d-block rounded img-fluid", id: "modal_camp_id_#{camp.id}_image_id_#{i+1}")%>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <%end%>


                <div class="col-lg-6 col-sm-12 mt-2">
                  <%= render partial: 'every_camp/camp_item_list', locals: {camp: camp} %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="card-body">
            <% if camp.area.present? %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i>
                <%= camp.area.name %>
              </p>
            <% else %>
              <p class="text-white-50"><i class="fas fa-map-marker-alt"></i> 未登録です</p>
            <% end%>
            <h2 class="card-title text-bold"><%= camp.title %></h2>
            <p class="card-text"><%= camp.note %></p>
          </div>
          <%end%>
        </div>
      </div>
    <% end %>

app/views/every_camp/_like.html.erb
<% if current_user.is_guest_user? %>
  <%= link_to user_every_camp_likes_path(current_user,camp),
              id: "js-like-button-#{camp.id}",
              method: :post,
              class: "float-right",
              data: { confirm: 'ユーザー登録してください' } do %>
      <div class="heart">
      <span class="heart_hover">いいね!の火を灯す</span>
      <span class="heart_count"><%= camp.likes.count %></span>
    </div>
  <% end %>
<% else %>
  <%= link_to user_every_camp_likes_path(current_user,camp),
              id: "js-like-button-#{camp.id}",
              method: :post,
              class: "float-right",
              remote: true do %>
  <div class="heart">
    <span class="heart_hover">いいね!の火を灯す</span>
    <span class="heart_count"><%= camp.likes.count %></span>
  </div>
  <% end %>
<% end %>

app/views/every_camp/_modal.html.erb
<!-- modal -->
<div id="modal01" class="c-modal js-modal">
  <div class="c-modal_bg js-modal-close">
  </div>
  <div class="c-modal_content">
    <div class="c-modal_content_inner">
      <div class="row">
        <div class="col">
          <a class="js-modal-close c-modal_close" href="">
          <span><i class="far fa-times-circle fa-lg"></i></span>
          </a>
          <br>
          <div id="modal_image_box">
            <div class="bigimg"><img src="" alt="" class="d-block mx-auto" style="max-width:90%; max-height:500px;"></div>
            <!--ここにモーダルウィンドウの内容が入ります-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ./modal -->

app/views/every_camp/_unlike.html.erb
<%= link_to user_every_camp_like_path(current_user,camp,current_user.likes.find_by(camp_id: camp.id)),
    id: "js-like-button-#{camp.id}",
    method: :delete,
    class: "float-right",
    remote: true do %>
      <div class="heart HeartAnimation">
        <span class="heart_count"><%= camp.likes.count %></span>
      </div>
<% end %>

app/views/every_camp/index.html.erb
<% set_meta_tags title: "#{t '.title'}" %>
<% content_for :title do%>
<%= t '.title' %>
<% end %>
<div class='container'>
  <div class='jscroll_list'>
    <div id='camp_list' class='jscroll pb-5'>
      <% if @camps.present? %>
        <%= render 'camp_list', {camps: @camps} %>
      <% else %>
        <h2> キャンプのキロクはまだありません</h2>
      <% end %>
    </div>
    <div class="insert_pagenation">
      <%= link_to_next_page @camps , '＋もっと見る', class: "next btn btn-outline-warning col-md-12", id: 'next', remote: true %>
    </div>
  </div>
  <%= render partial: 'modal' %>
</div>

app/views/every_camp/index.js.erb
$('#camp_list').append("<%= j(render 'camp_list') %>");
$('#next').remove();
$('.insert_pagenation').append("<%= j(link_to_next_page @camps, '＋もっと見る', class: 'next btn btn-outline-warning col-md-12', id: 'next', remote: true) %>");